spring:
  profiles:
    active: postgre
  datasource:
    url: jdbc:postgresql://localhost:5432/alexb
    password: c56810584
    username: alex581
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  devtools:
    restart:
      enabled: false
alexb:
  queue:
    name: EmpQueue