spring:
  profiles:
    active: @profile@
  datasource:
    url: @dburl@
    password: @password@
    username: @username@
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
  devtools:
    restart:
      enabled: false
alexb:
  queue:
    name: EmpQueue