spring:
  profiles:
    active: @profile@
  datasource:
    url: @dburl@
    password: @password@
    username: @username@
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

alexb:
  queue:
    name: EmpQueue