spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect:org.hibernate.dialect: PostgreSQL95Dialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true