alexb:
  queue:
    name: EmpQueue
    exchange: EmployeeExchange
    key: Emp
server:
  port: 8081
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  devtools:
    restart:
      enabled: false
logging:
  level:
    org.springframework.amqp: trace